// Music markets with coordinates — the more regions, the denser the globe
export const REGIONS = [
  // Americas
  { code: 'US', lat: 40.7, lng: -74, name: 'New York' },
  { code: 'US', lat: 34, lng: -118.2, name: 'Los Angeles' },
  { code: 'US', lat: 41.9, lng: -87.6, name: 'Chicago' },
  { code: 'US', lat: 29.8, lng: -95.4, name: 'Houston' },
  { code: 'US', lat: 33.4, lng: -112, name: 'Phoenix' },
  { code: 'US', lat: 25.8, lng: -80.2, name: 'Miami' },
  { code: 'US', lat: 36.2, lng: -86.8, name: 'Nashville' },
  { code: 'US', lat: 47.6, lng: -122.3, name: 'Seattle' },
  { code: 'US', lat: 30, lng: -90, name: 'New Orleans' },
  { code: 'US', lat: 39.7, lng: -105, name: 'Denver' },
  { code: 'CA', lat: 43.7, lng: -79.4, name: 'Toronto' },
  { code: 'CA', lat: 45.5, lng: -73.6, name: 'Montreal' },
  { code: 'CA', lat: 49.3, lng: -123.1, name: 'Vancouver' },
  { code: 'MX', lat: 19.4, lng: -99.1, name: 'Mexico City' },
  { code: 'MX', lat: 20.7, lng: -103.3, name: 'Guadalajara' },
  { code: 'BR', lat: -23.5, lng: -46.6, name: 'São Paulo' },
  { code: 'BR', lat: -22.9, lng: -43.2, name: 'Rio de Janeiro' },
  { code: 'BR', lat: -12.97, lng: -38.5, name: 'Salvador' },
  { code: 'AR', lat: -34.6, lng: -58.4, name: 'Buenos Aires' },
  { code: 'CO', lat: 4.7, lng: -74.1, name: 'Bogotá' },
  { code: 'CO', lat: 6.2, lng: -75.6, name: 'Medellín' },
  { code: 'CL', lat: -33.4, lng: -70.6, name: 'Santiago' },
  { code: 'PE', lat: -12, lng: -77, name: 'Lima' },
  { code: 'JM', lat: 18, lng: -76.8, name: 'Kingston' },
  { code: 'CU', lat: 23.1, lng: -82.4, name: 'Havana' },
  { code: 'PR', lat: 18.5, lng: -66.1, name: 'San Juan' },
  { code: 'TT', lat: 10.7, lng: -61.5, name: 'Port of Spain' },
  // Europe
  { code: 'GB', lat: 51.5, lng: -0.1, name: 'London' },
  { code: 'GB', lat: 53.5, lng: -2.2, name: 'Manchester' },
  { code: 'GB', lat: 55.95, lng: -3.2, name: 'Edinburgh' },
  { code: 'FR', lat: 48.9, lng: 2.35, name: 'Paris' },
  { code: 'FR', lat: 43.3, lng: 5.4, name: 'Marseille' },
  { code: 'DE', lat: 52.5, lng: 13.4, name: 'Berlin' },
  { code: 'DE', lat: 48.1, lng: 11.6, name: 'Munich' },
  { code: 'DE', lat: 50.1, lng: 8.7, name: 'Frankfurt' },
  { code: 'ES', lat: 40.4, lng: -3.7, name: 'Madrid' },
  { code: 'ES', lat: 41.4, lng: 2.2, name: 'Barcelona' },
  { code: 'IT', lat: 41.9, lng: 12.5, name: 'Rome' },
  { code: 'IT', lat: 45.5, lng: 9.2, name: 'Milan' },
  { code: 'NL', lat: 52.4, lng: 4.9, name: 'Amsterdam' },
  { code: 'SE', lat: 59.3, lng: 18.1, name: 'Stockholm' },
  { code: 'NO', lat: 59.9, lng: 10.75, name: 'Oslo' },
  { code: 'DK', lat: 55.7, lng: 12.6, name: 'Copenhagen' },
  { code: 'FI', lat: 60.2, lng: 24.9, name: 'Helsinki' },
  { code: 'PT', lat: 38.7, lng: -9.1, name: 'Lisbon' },
  { code: 'IE', lat: 53.35, lng: -6.26, name: 'Dublin' },
  { code: 'BE', lat: 50.85, lng: 4.35, name: 'Brussels' },
  { code: 'AT', lat: 48.2, lng: 16.4, name: 'Vienna' },
  { code: 'CH', lat: 47.4, lng: 8.5, name: 'Zürich' },
  { code: 'PL', lat: 52.2, lng: 21, name: 'Warsaw' },
  { code: 'CZ', lat: 50.1, lng: 14.4, name: 'Prague' },
  { code: 'GR', lat: 37.98, lng: 23.7, name: 'Athens' },
  { code: 'RO', lat: 44.4, lng: 26.1, name: 'Bucharest' },
  { code: 'HU', lat: 47.5, lng: 19.04, name: 'Budapest' },
  { code: 'UA', lat: 50.45, lng: 30.5, name: 'Kyiv' },
  { code: 'RU', lat: 55.8, lng: 37.6, name: 'Moscow' },
  { code: 'RU', lat: 59.9, lng: 30.3, name: 'St Petersburg' },
  { code: 'TR', lat: 41, lng: 29, name: 'Istanbul' },
  { code: 'TR', lat: 39.9, lng: 32.9, name: 'Ankara' },
  // Africa
  { code: 'NG', lat: 6.5, lng: 3.4, name: 'Lagos' },
  { code: 'NG', lat: 9.06, lng: 7.5, name: 'Abuja' },
  { code: 'ZA', lat: -33.9, lng: 18.4, name: 'Cape Town' },
  { code: 'ZA', lat: -26.2, lng: 28.05, name: 'Johannesburg' },
  { code: 'GH', lat: 5.6, lng: -0.19, name: 'Accra' },
  { code: 'KE', lat: -1.3, lng: 36.8, name: 'Nairobi' },
  { code: 'TZ', lat: -6.8, lng: 39.3, name: 'Dar es Salaam' },
  { code: 'EG', lat: 30, lng: 31.24, name: 'Cairo' },
  { code: 'MA', lat: 33.6, lng: -7.6, name: 'Casablanca' },
  { code: 'SN', lat: 14.7, lng: -17.5, name: 'Dakar' },
  { code: 'ET', lat: 9, lng: 38.7, name: 'Addis Ababa' },
  { code: 'CI', lat: 5.3, lng: -4, name: 'Abidjan' },
  // Middle East
  { code: 'AE', lat: 25.2, lng: 55.3, name: 'Dubai' },
  { code: 'SA', lat: 24.7, lng: 46.7, name: 'Riyadh' },
  { code: 'IL', lat: 32.1, lng: 34.8, name: 'Tel Aviv' },
  { code: 'LB', lat: 33.9, lng: 35.5, name: 'Beirut' },
  // Asia
  { code: 'IN', lat: 19.1, lng: 72.9, name: 'Mumbai' },
  { code: 'IN', lat: 28.6, lng: 77.2, name: 'New Delhi' },
  { code: 'IN', lat: 13, lng: 77.6, name: 'Bangalore' },
  { code: 'IN', lat: 22.6, lng: 88.4, name: 'Kolkata' },
  { code: 'IN', lat: 13.1, lng: 80.3, name: 'Chennai' },
  { code: 'JP', lat: 35.7, lng: 139.7, name: 'Tokyo' },
  { code: 'JP', lat: 34.7, lng: 135.5, name: 'Osaka' },
  { code: 'KR', lat: 37.6, lng: 127, name: 'Seoul' },
  { code: 'KR', lat: 35.2, lng: 129, name: 'Busan' },
  { code: 'CN', lat: 31.2, lng: 121.5, name: 'Shanghai' },
  { code: 'CN', lat: 39.9, lng: 116.4, name: 'Beijing' },
  { code: 'CN', lat: 22.5, lng: 114.1, name: 'Shenzhen' },
  { code: 'HK', lat: 22.3, lng: 114.2, name: 'Hong Kong' },
  { code: 'TW', lat: 25, lng: 121.5, name: 'Taipei' },
  { code: 'TH', lat: 13.75, lng: 100.5, name: 'Bangkok' },
  { code: 'VN', lat: 10.8, lng: 106.6, name: 'Ho Chi Minh City' },
  { code: 'VN', lat: 21, lng: 105.85, name: 'Hanoi' },
  { code: 'ID', lat: -6.2, lng: 106.85, name: 'Jakarta' },
  { code: 'ID', lat: -8.65, lng: 115.2, name: 'Bali' },
  { code: 'PH', lat: 14.6, lng: 121, name: 'Manila' },
  { code: 'MY', lat: 3.1, lng: 101.7, name: 'Kuala Lumpur' },
  { code: 'SG', lat: 1.35, lng: 103.8, name: 'Singapore' },
  { code: 'PK', lat: 24.9, lng: 67, name: 'Karachi' },
  { code: 'PK', lat: 31.55, lng: 74.35, name: 'Lahore' },
  { code: 'BD', lat: 23.8, lng: 90.4, name: 'Dhaka' },
  { code: 'LK', lat: 6.9, lng: 79.85, name: 'Colombo' },
  { code: 'NP', lat: 27.7, lng: 85.3, name: 'Kathmandu' },
  // Oceania
  { code: 'AU', lat: -33.9, lng: 151.2, name: 'Sydney' },
  { code: 'AU', lat: -37.8, lng: 145, name: 'Melbourne' },
  { code: 'NZ', lat: -36.85, lng: 174.8, name: 'Auckland' },
];

// Region-specific music genres — makes each region sound authentic
export const REGIONAL_GENRES: Record<string, string[]> = {
  US: ['hip hop', 'country', 'r&b', 'jazz', 'blues', 'rock', 'indie', 'gospel', 'trap'],
  CA: ['indie rock', 'electronic', 'hip hop', 'folk', 'alternative'],
  MX: ['regional mexicano', 'corridos', 'cumbia', 'mariachi', 'banda', 'norteño'],
  BR: ['sertanejo', 'funk carioca', 'bossa nova', 'mpb', 'samba', 'pagode', 'forró', 'axé'],
  AR: ['tango', 'cumbia argentina', 'rock argentino', 'folklore argentino', 'trap latino'],
  CO: ['reggaeton', 'vallenato', 'cumbia', 'salsa', 'champeta'],
  CL: ['cumbia chilena', 'rock en español', 'trap latino'],
  PE: ['cumbia peruana', 'huayno', 'salsa', 'criolla'],
  JM: ['reggae', 'dancehall', 'ska', 'dub', 'roots reggae'],
  CU: ['son cubano', 'salsa', 'timba', 'bolero', 'rumba'],
  PR: ['reggaeton', 'salsa', 'trap latino', 'bachata'],
  TT: ['soca', 'calypso', 'chutney', 'dancehall'],
  GB: ['grime', 'drum and bass', 'uk garage', 'britpop', 'shoegaze', 'post-punk', 'uk drill'],
  FR: ['french rap', 'chanson', 'french house', 'variété française', 'electro'],
  DE: ['techno', 'krautrock', 'schlager', 'german rap', 'minimal techno', 'industrial'],
  ES: ['flamenco', 'reggaeton', 'spanish pop', 'rumba', 'latin trap'],
  IT: ['italian pop', 'opera', 'italo disco', 'italian rap', 'cantautore'],
  NL: ['dutch edm', 'hardstyle', 'gabber', 'dutch hip hop', 'trance'],
  SE: ['swedish pop', 'death metal', 'melodic death metal', 'synth pop', 'swedish house'],
  NO: ['black metal', 'norwegian pop', 'nordic folk', 'electronic'],
  DK: ['danish pop', 'nordic electronic', 'danish rap'],
  FI: ['finnish metal', 'suomipop', 'finnish folk', 'finnish tango'],
  PT: ['fado', 'portuguese pop', 'kizomba', 'pimba'],
  IE: ['irish folk', 'celtic', 'irish rock', 'trad irish'],
  BE: ['belgian edm', 'new beat', 'belgian hip hop'],
  AT: ['austrian pop', 'waltz', 'austro pop'],
  CH: ['swiss german rap', 'yodel', 'swiss folk'],
  PL: ['polish rap', 'disco polo', 'polish rock'],
  CZ: ['czech rock', 'czech hip hop'],
  GR: ['rebetiko', 'greek pop', 'laiko', 'entechno'],
  RO: ['manele', 'romanian pop', 'romanian house'],
  HU: ['hungarian folk', 'magyar rap'],
  UA: ['ukrainian rap', 'ukrainian folk', 'ukrainian pop'],
  RU: ['russian rap', 'russian pop', 'russian rock', 'russian electronic'],
  TR: ['turkish pop', 'arabesk', 'anatolian rock', 'turkish rap', 'ottoman classical'],
  NG: ['afrobeats', 'afropop', 'highlife', 'fuji', 'juju', 'afro house', 'amapiano'],
  ZA: ['amapiano', 'gqom', 'kwaito', 'south african house', 'maskandi'],
  GH: ['highlife', 'afrobeats', 'hiplife', 'azonto'],
  KE: ['gengetone', 'benga', 'kenyan hip hop', 'genge'],
  TZ: ['bongo flava', 'taarab', 'singeli'],
  EG: ['shaabi', 'mahraganat', 'arabic pop', 'rai'],
  MA: ['gnawa', 'rai', 'chaabi', 'moroccan rap'],
  SN: ['mbalax', 'afro manding', 'senegalese rap'],
  ET: ['ethio jazz', 'ethiopian pop'],
  CI: ['coupé-décalé', 'zouglou', 'afrobeats'],
  AE: ['arabic pop', 'khaleeji', 'arabic electronic'],
  SA: ['khaleeji', 'arabic pop', 'saudi rap'],
  IL: ['israeli pop', 'mizrahi', 'israeli rock', 'middle eastern electronic'],
  LB: ['arabic pop', 'lebanese dabke', 'arabic r&b'],
  IN: ['bollywood', 'indian classical', 'punjabi pop', 'bhangra', 'indian hip hop', 'carnatic', 'tamil pop', 'telugu pop'],
  JP: ['j-pop', 'j-rock', 'city pop', 'anime', 'japanese jazz', 'visual kei', 'enka', 'shibuya kei'],
  KR: ['k-pop', 'k-hip hop', 'k-indie', 'korean r&b', 'k-rock', 'trot'],
  CN: ['c-pop', 'mandopop', 'chinese rock', 'chinese hip hop'],
  HK: ['cantopop', 'hong kong rock'],
  TW: ['mandopop', 'taiwanese pop', 'taiwanese indie'],
  TH: ['thai pop', 'luk thung', 'mor lam', 'thai hip hop'],
  VN: ['v-pop', 'vietnamese ballad', 'vietnamese rap'],
  ID: ['indonesian pop', 'dangdut', 'indonesian rock', 'gamelan'],
  PH: ['opm', 'filipino pop', 'filipino rap', 'filipino rock'],
  MY: ['malaysian pop', 'malay rock'],
  SG: ['singaporean pop', 'mandopop'],
  PK: ['qawwali', 'pakistani pop', 'coke studio pakistan', 'ghazal'],
  BD: ['bangla pop', 'baul', 'bangladeshi rock'],
  LK: ['sinhala pop', 'baila'],
  NP: ['nepali pop', 'nepali rock', 'lok dohori'],
  AU: ['australian rock', 'australian hip hop', 'australian indie', 'australian country'],
  NZ: ['new zealand reggae', 'nz indie', 'maori music'],
};